// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package dbgen

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO users (email, display_name, role, password_hash)
VALUES (?, ?, 'customer', ?)
ON CONFLICT(email) DO NOTHING
RETURNING id
`

type CreateCustomerParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCustomer, arg.Email, arg.DisplayName, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
  token_hash,
  user_id,
  csrf_token,
  expires_at,
  last_authenticated_at,
  created_at
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash           string `json:"token_hash"`
	UserID              int64  `json:"user_id"`
	CsrfToken           string `json:"csrf_token"`
	ExpiresAt           string `json:"expires_at"`
	LastAuthenticatedAt string `json:"last_authenticated_at"`
	CreatedAt           string `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CsrfToken,
		arg.ExpiresAt,
		arg.LastAuthenticatedAt,
		arg.CreatedAt,
	)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT user_id, csrf_token, expires_at, revoked_at, last_authenticated_at, created_at
FROM sessions
WHERE token_hash = ?
`

type GetSessionByTokenHashRow struct {
	UserID              int64   `json:"user_id"`
	CsrfToken           string  `json:"csrf_token"`
	ExpiresAt           string  `json:"expires_at"`
	RevokedAt           *string `json:"revoked_at"`
	LastAuthenticatedAt string  `json:"last_authenticated_at"`
	CreatedAt           string  `json:"created_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.UserID,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastAuthenticatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id,
  email,
  display_name,
  role,
  password_hash,
  CASE WHEN totp_secret IS NOT NULL OR totp_secret_encrypted IS NOT NULL THEN 1 ELSE 0 END AS has_totp,
  CASE WHEN pending_totp_secret IS NOT NULL OR pending_totp_secret_encrypted IS NOT NULL THEN 1 ELSE 0 END AS has_pending_totp,
  created_at,
  updated_at
FROM users
WHERE email = ?
`

type GetUserByEmailRow struct {
	ID             int64  `json:"id"`
	Email          string `json:"email"`
	DisplayName    string `json:"display_name"`
	Role           string `json:"role"`
	PasswordHash   string `json:"password_hash"`
	HasTotp        int64  `json:"has_totp"`
	HasPendingTotp int64  `json:"has_pending_totp"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.HasTotp,
		&i.HasPendingTotp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id,
  email,
  display_name,
  role,
  password_hash,
  CASE WHEN totp_secret IS NOT NULL OR totp_secret_encrypted IS NOT NULL THEN 1 ELSE 0 END AS has_totp,
  CASE WHEN pending_totp_secret IS NOT NULL OR pending_totp_secret_encrypted IS NOT NULL THEN 1 ELSE 0 END AS has_pending_totp,
  created_at,
  updated_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID             int64  `json:"id"`
	Email          string `json:"email"`
	DisplayName    string `json:"display_name"`
	Role           string `json:"role"`
	PasswordHash   string `json:"password_hash"`
	HasTotp        int64  `json:"has_totp"`
	HasPendingTotp int64  `json:"has_pending_totp"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.HasTotp,
		&i.HasPendingTotp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartQuantities = `-- name: ListCartQuantities :many
SELECT product_id, quantity
FROM cart_items
WHERE user_id = ?
`

type ListCartQuantitiesRow struct {
	ProductID int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}

func (q *Queries) ListCartQuantities(ctx context.Context, userID int64) ([]ListCartQuantitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCartQuantities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartQuantitiesRow
	for rows.Next() {
		var i ListCartQuantitiesRow
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllActiveSessions = `-- name: RevokeAllActiveSessions :execrows
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE revoked_at IS NULL
`

func (q *Queries) RevokeAllActiveSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAllActiveSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = ?
WHERE token_hash = ?
`

type RevokeSessionParams struct {
	RevokedAt *string `json:"revoked_at"`
	TokenHash string  `json:"token_hash"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.RevokedAt, arg.TokenHash)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE OR IGNORE users
SET email = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id
`

type UpdateUserEmailParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateUserEmail, arg.Email, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}
