// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package dbgen

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, image_path, price_cents, cost_cents, inventory_count, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, image_path, price_cents, cost_cents, inventory_count, is_active, created_at
`

type CreateProductParams struct {
	Name           string `json:"name"`
	Description    string `json:"description"`
	ImagePath      string `json:"image_path"`
	PriceCents     int64  `json:"price_cents"`
	CostCents      int64  `json:"cost_cents"`
	InventoryCount int64  `json:"inventory_count"`
	IsActive       int64  `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.ImagePath,
		arg.PriceCents,
		arg.CostCents,
		arg.InventoryCount,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImagePath,
		&i.PriceCents,
		&i.CostCents,
		&i.InventoryCount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, image_path, price_cents, cost_cents, inventory_count, is_active, created_at
FROM products
WHERE id = ?
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImagePath,
		&i.PriceCents,
		&i.CostCents,
		&i.InventoryCount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT id, name, description, image_path, price_cents, cost_cents, inventory_count, is_active, created_at
FROM products
ORDER BY name
`

func (q *Queries) ListAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImagePath,
			&i.PriceCents,
			&i.CostCents,
			&i.InventoryCount,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
  name = ?,
  description = ?,
  image_path = ?,
  price_cents = ?,
  cost_cents = ?,
  inventory_count = ?,
  is_active = ?
WHERE id = ?
RETURNING id, name, description, image_path, price_cents, cost_cents, inventory_count, is_active, created_at
`

type UpdateProductParams struct {
	Name           string `json:"name"`
	Description    string `json:"description"`
	ImagePath      string `json:"image_path"`
	PriceCents     int64  `json:"price_cents"`
	CostCents      int64  `json:"cost_cents"`
	InventoryCount int64  `json:"inventory_count"`
	IsActive       int64  `json:"is_active"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.ImagePath,
		arg.PriceCents,
		arg.CostCents,
		arg.InventoryCount,
		arg.IsActive,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImagePath,
		&i.PriceCents,
		&i.CostCents,
		&i.InventoryCount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
