// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api.sql

package dbgen

import (
	"context"
)

const consumeAPIKeyQuota = `-- name: ConsumeAPIKeyQuota :one
INSERT INTO api_key_usage (api_key_id, period_start, request_count)
VALUES (?, ?, 1)
ON CONFLICT (api_key_id, period_start) DO UPDATE
SET request_count = request_count + 1
WHERE request_count < 5
RETURNING request_count
`

type ConsumeAPIKeyQuotaParams struct {
	ApiKeyID    int64  `json:"api_key_id"`
	PeriodStart string `json:"period_start"`
}

func (q *Queries) ConsumeAPIKeyQuota(ctx context.Context, arg ConsumeAPIKeyQuotaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, consumeAPIKeyQuota, arg.ApiKeyID, arg.PeriodStart)
	var request_count int64
	err := row.Scan(&request_count)
	return request_count, err
}

const getAPIKeyUsage = `-- name: GetAPIKeyUsage :one
SELECT request_count
FROM api_key_usage
WHERE api_key_id = ? AND period_start = ?
`

type GetAPIKeyUsageParams struct {
	ApiKeyID    int64  `json:"api_key_id"`
	PeriodStart string `json:"period_start"`
}

func (q *Queries) GetAPIKeyUsage(ctx context.Context, arg GetAPIKeyUsageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyUsage, arg.ApiKeyID, arg.PeriodStart)
	var request_count int64
	err := row.Scan(&request_count)
	return request_count, err
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, name, key_hash, scope, revoked_at, created_at
FROM api_keys
WHERE key_hash = ?
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getActiveAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Scope,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
