// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package dbgen

import (
	"context"
	"database/sql"
)

const activeCartProductExists = `-- name: ActiveCartProductExists :one
SELECT EXISTS(
  SELECT 1
  FROM products
  WHERE id = ? AND is_active = 1
)
`

func (q *Queries) ActiveCartProductExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeCartProductExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const addProductToCart = `-- name: AddProductToCart :execresult
INSERT INTO cart_items (user_id, product_id, quantity)
SELECT ?1, products.id, ?2
FROM products
WHERE products.id = ?3
  AND products.is_active = 1
  AND products.inventory_count >= ?2
ON CONFLICT (user_id, product_id) DO UPDATE SET
  quantity = cart_items.quantity + excluded.quantity,
  updated_at = CURRENT_TIMESTAMP
WHERE cart_items.quantity + excluded.quantity <= 99
  AND cart_items.quantity + excluded.quantity <= (
    SELECT inventory_count
    FROM products
    WHERE products.id = excluded.product_id
      AND products.is_active = 1
  )
`

type AddProductToCartParams struct {
	UserID    int64 `json:"user_id"`
	Quantity  int64 `json:"quantity"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) AddProductToCart(ctx context.Context, arg AddProductToCartParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProductToCart, arg.UserID, arg.Quantity, arg.ProductID)
}

const listCartItems = `-- name: ListCartItems :many
SELECT
  cart_items.id,
  cart_items.user_id,
  cart_items.product_id,
  cart_items.quantity,
  cart_items.created_at,
  cart_items.updated_at,
  products.name,
  products.image_path,
  products.price_cents,
  products.inventory_count,
  products.is_active,
  products.price_cents * cart_items.quantity AS line_total_cents
FROM cart_items
JOIN products ON products.id = cart_items.product_id
WHERE cart_items.user_id = ?
ORDER BY cart_items.created_at
`

type ListCartItemsRow struct {
	ID             int64  `json:"id"`
	UserID         int64  `json:"user_id"`
	ProductID      int64  `json:"product_id"`
	Quantity       int64  `json:"quantity"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
	Name           string `json:"name"`
	ImagePath      string `json:"image_path"`
	PriceCents     int64  `json:"price_cents"`
	InventoryCount int64  `json:"inventory_count"`
	IsActive       int64  `json:"is_active"`
	LineTotalCents int64  `json:"line_total_cents"`
}

func (q *Queries) ListCartItems(ctx context.Context, userID int64) ([]ListCartItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsRow
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.ImagePath,
			&i.PriceCents,
			&i.InventoryCount,
			&i.IsActive,
			&i.LineTotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE user_id = ? AND product_id = ?
`

type RemoveCartItemParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.ExecContext(ctx, removeCartItem, arg.UserID, arg.ProductID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :execresult
UPDATE cart_items
SET quantity = ?1, updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?2
  AND product_id = ?3
  AND ?1 <= (
    SELECT inventory_count
    FROM products
    WHERE products.id = cart_items.product_id
      AND products.is_active = 1
  )
`

type UpdateCartItemQuantityParams struct {
	Quantity  int64 `json:"quantity"`
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCartItemQuantity, arg.Quantity, arg.UserID, arg.ProductID)
}
