// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa.sql

package dbgen

import (
	"context"
	"database/sql"
)

const clearTOTPSecrets = `-- name: ClearTOTPSecrets :exec
UPDATE users
SET
  totp_secret = NULL,
  pending_totp_secret = NULL,
  totp_secret_encrypted = NULL,
  pending_totp_secret_encrypted = NULL,
  last_totp_step = NULL,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) ClearTOTPSecrets(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearTOTPSecrets, id)
	return err
}

const confirmTOTPSecret = `-- name: ConfirmTOTPSecret :exec
UPDATE users
SET
  totp_secret_encrypted = pending_totp_secret_encrypted,
  pending_totp_secret_encrypted = NULL,
  last_totp_step = NULL,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) ConfirmTOTPSecret(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, confirmTOTPSecret, id)
	return err
}

const consumeTOTPBackupCode = `-- name: ConsumeTOTPBackupCode :execresult
UPDATE totp_backup_codes
SET used_at = CURRENT_TIMESTAMP
WHERE user_id = ?1
  AND code_hash = ?2
  AND used_at IS NULL
`

type ConsumeTOTPBackupCodeParams struct {
	UserID   int64  `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) ConsumeTOTPBackupCode(ctx context.Context, arg ConsumeTOTPBackupCodeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeTOTPBackupCode, arg.UserID, arg.CodeHash)
}

const consumeTOTPStep = `-- name: ConsumeTOTPStep :execresult
UPDATE users
SET last_totp_step = ?1
WHERE id = ?2
  AND (last_totp_step IS NULL OR last_totp_step < ?1)
`

type ConsumeTOTPStepParams struct {
	TimeStep *int64 `json:"time_step"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) ConsumeTOTPStep(ctx context.Context, arg ConsumeTOTPStepParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeTOTPStep, arg.TimeStep, arg.UserID)
}

const countRecentMFARecoveryFailures = `-- name: CountRecentMFARecoveryFailures :one
SELECT COUNT(*)
FROM mfa_recovery_attempts
WHERE email = ?1
  AND success = 0
  AND created_at > ?2
`

type CountRecentMFARecoveryFailuresParams struct {
	Email  string `json:"email"`
	Cutoff string `json:"cutoff"`
}

func (q *Queries) CountRecentMFARecoveryFailures(ctx context.Context, arg CountRecentMFARecoveryFailuresParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentMFARecoveryFailures, arg.Email, arg.Cutoff)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTOTPBackupCode = `-- name: CreateTOTPBackupCode :exec
INSERT INTO totp_backup_codes (user_id, code_hash)
VALUES (?, ?)
`

type CreateTOTPBackupCodeParams struct {
	UserID   int64  `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) CreateTOTPBackupCode(ctx context.Context, arg CreateTOTPBackupCodeParams) error {
	_, err := q.db.ExecContext(ctx, createTOTPBackupCode, arg.UserID, arg.CodeHash)
	return err
}

const createTOTPLoginChallenge = `-- name: CreateTOTPLoginChallenge :exec
INSERT INTO totp_login_challenges (
  token_hash,
  user_id,
  return_to,
  attempts_remaining,
  expires_at,
  created_at
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTOTPLoginChallengeParams struct {
	TokenHash         string `json:"token_hash"`
	UserID            int64  `json:"user_id"`
	ReturnTo          string `json:"return_to"`
	AttemptsRemaining int64  `json:"attempts_remaining"`
	ExpiresAt         string `json:"expires_at"`
	CreatedAt         string `json:"created_at"`
}

func (q *Queries) CreateTOTPLoginChallenge(ctx context.Context, arg CreateTOTPLoginChallengeParams) error {
	_, err := q.db.ExecContext(ctx, createTOTPLoginChallenge,
		arg.TokenHash,
		arg.UserID,
		arg.ReturnTo,
		arg.AttemptsRemaining,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteTOTPBackupCodesForUser = `-- name: DeleteTOTPBackupCodesForUser :exec
DELETE FROM totp_backup_codes
WHERE user_id = ?
`

func (q *Queries) DeleteTOTPBackupCodesForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTOTPBackupCodesForUser, userID)
	return err
}

const deleteTOTPLoginChallenge = `-- name: DeleteTOTPLoginChallenge :exec
DELETE FROM totp_login_challenges
WHERE token_hash = ?
`

func (q *Queries) DeleteTOTPLoginChallenge(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteTOTPLoginChallenge, tokenHash)
	return err
}

const deleteTOTPLoginChallengesForUser = `-- name: DeleteTOTPLoginChallengesForUser :exec
DELETE FROM totp_login_challenges
WHERE user_id = ?
`

func (q *Queries) DeleteTOTPLoginChallengesForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTOTPLoginChallengesForUser, userID)
	return err
}

const getPendingTOTPSecret = `-- name: GetPendingTOTPSecret :one
SELECT pending_totp_secret_encrypted
FROM users
WHERE id = ? AND pending_totp_secret_encrypted IS NOT NULL
`

func (q *Queries) GetPendingTOTPSecret(ctx context.Context, id int64) (*string, error) {
	row := q.db.QueryRowContext(ctx, getPendingTOTPSecret, id)
	var pending_totp_secret_encrypted *string
	err := row.Scan(&pending_totp_secret_encrypted)
	return pending_totp_secret_encrypted, err
}

const getTOTPLoginChallenge = `-- name: GetTOTPLoginChallenge :one
SELECT user_id, return_to, attempts_remaining, expires_at
FROM totp_login_challenges
WHERE token_hash = ?
`

type GetTOTPLoginChallengeRow struct {
	UserID            int64  `json:"user_id"`
	ReturnTo          string `json:"return_to"`
	AttemptsRemaining int64  `json:"attempts_remaining"`
	ExpiresAt         string `json:"expires_at"`
}

func (q *Queries) GetTOTPLoginChallenge(ctx context.Context, tokenHash string) (GetTOTPLoginChallengeRow, error) {
	row := q.db.QueryRowContext(ctx, getTOTPLoginChallenge, tokenHash)
	var i GetTOTPLoginChallengeRow
	err := row.Scan(
		&i.UserID,
		&i.ReturnTo,
		&i.AttemptsRemaining,
		&i.ExpiresAt,
	)
	return i, err
}

const getTOTPSecret = `-- name: GetTOTPSecret :one
SELECT totp_secret_encrypted
FROM users
WHERE id = ? AND totp_secret_encrypted IS NOT NULL
`

func (q *Queries) GetTOTPSecret(ctx context.Context, id int64) (*string, error) {
	row := q.db.QueryRowContext(ctx, getTOTPSecret, id)
	var totp_secret_encrypted *string
	err := row.Scan(&totp_secret_encrypted)
	return totp_secret_encrypted, err
}

const listLegacyTOTPSecrets = `-- name: ListLegacyTOTPSecrets :many
SELECT
  id,
  totp_secret,
  pending_totp_secret,
  totp_secret_encrypted,
  pending_totp_secret_encrypted
FROM users
WHERE totp_secret IS NOT NULL OR pending_totp_secret IS NOT NULL
`

type ListLegacyTOTPSecretsRow struct {
	ID                         int64   `json:"id"`
	TotpSecret                 *string `json:"totp_secret"`
	PendingTotpSecret          *string `json:"pending_totp_secret"`
	TotpSecretEncrypted        *string `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted *string `json:"pending_totp_secret_encrypted"`
}

func (q *Queries) ListLegacyTOTPSecrets(ctx context.Context) ([]ListLegacyTOTPSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyTOTPSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegacyTOTPSecretsRow
	for rows.Next() {
		var i ListLegacyTOTPSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.TotpSecret,
			&i.PendingTotpSecret,
			&i.TotpSecretEncrypted,
			&i.PendingTotpSecretEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateTOTPSecrets = `-- name: MigrateTOTPSecrets :exec
UPDATE users
SET
  totp_secret = NULL,
  pending_totp_secret = NULL,
  totp_secret_encrypted = ?,
  pending_totp_secret_encrypted = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MigrateTOTPSecretsParams struct {
	TotpSecretEncrypted        *string `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted *string `json:"pending_totp_secret_encrypted"`
	ID                         int64   `json:"id"`
}

func (q *Queries) MigrateTOTPSecrets(ctx context.Context, arg MigrateTOTPSecretsParams) error {
	_, err := q.db.ExecContext(ctx, migrateTOTPSecrets, arg.TotpSecretEncrypted, arg.PendingTotpSecretEncrypted, arg.ID)
	return err
}

const pruneMFARecoveryAttempts = `-- name: PruneMFARecoveryAttempts :exec
DELETE FROM mfa_recovery_attempts
WHERE created_at <= ?
`

func (q *Queries) PruneMFARecoveryAttempts(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, pruneMFARecoveryAttempts, createdAt)
	return err
}

const pruneTOTPLoginChallenges = `-- name: PruneTOTPLoginChallenges :exec
DELETE FROM totp_login_challenges
WHERE attempts_remaining <= 0 OR expires_at <= ?
`

func (q *Queries) PruneTOTPLoginChallenges(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, pruneTOTPLoginChallenges, expiresAt)
	return err
}

const recordMFARecoveryAttempt = `-- name: RecordMFARecoveryAttempt :exec
INSERT INTO mfa_recovery_attempts (email, user_id, success, created_at)
VALUES (?, ?, ?, ?)
`

type RecordMFARecoveryAttemptParams struct {
	Email     string `json:"email"`
	UserID    *int64 `json:"user_id"`
	Success   int64  `json:"success"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) RecordMFARecoveryAttempt(ctx context.Context, arg RecordMFARecoveryAttemptParams) error {
	_, err := q.db.ExecContext(ctx, recordMFARecoveryAttempt,
		arg.Email,
		arg.UserID,
		arg.Success,
		arg.CreatedAt,
	)
	return err
}

const recordTOTPLoginChallengeFailure = `-- name: RecordTOTPLoginChallengeFailure :one
UPDATE totp_login_challenges
SET attempts_remaining = attempts_remaining - 1
WHERE token_hash = ?1
  AND attempts_remaining > 0
  AND expires_at > ?2
RETURNING attempts_remaining
`

type RecordTOTPLoginChallengeFailureParams struct {
	TokenHash string `json:"token_hash"`
	Now       string `json:"now"`
}

func (q *Queries) RecordTOTPLoginChallengeFailure(ctx context.Context, arg RecordTOTPLoginChallengeFailureParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordTOTPLoginChallengeFailure, arg.TokenHash, arg.Now)
	var attempts_remaining int64
	err := row.Scan(&attempts_remaining)
	return attempts_remaining, err
}

const setPendingTOTPSecret = `-- name: SetPendingTOTPSecret :exec
UPDATE users
SET pending_totp_secret_encrypted = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetPendingTOTPSecretParams struct {
	PendingTotpSecretEncrypted *string `json:"pending_totp_secret_encrypted"`
	ID                         int64   `json:"id"`
}

func (q *Queries) SetPendingTOTPSecret(ctx context.Context, arg SetPendingTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, setPendingTOTPSecret, arg.PendingTotpSecretEncrypted, arg.ID)
	return err
}
