// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

type ApiKey struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	KeyHash   string  `json:"key_hash"`
	Scope     string  `json:"scope"`
	RevokedAt *string `json:"revoked_at"`
	CreatedAt string  `json:"created_at"`
}

type ApiKeyUsage struct {
	ApiKeyID     int64  `json:"api_key_id"`
	PeriodStart  string `json:"period_start"`
	RequestCount int64  `json:"request_count"`
}

type CartItem struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	ProductID int64  `json:"product_id"`
	Quantity  int64  `json:"quantity"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ImportedTaxDocument struct {
	ID               int64  `json:"id"`
	ImportedByUserID int64  `json:"imported_by_user_id"`
	OriginalName     string `json:"original_name"`
	StoragePath      string `json:"storage_path"`
	ContentType      string `json:"content_type"`
	CreatedAt        string `json:"created_at"`
}

type MfaRecoveryAttempt struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	UserID    *int64 `json:"user_id"`
	Success   int64  `json:"success"`
	CreatedAt string `json:"created_at"`
}

type Order struct {
	ID                       int64   `json:"id"`
	UserID                   int64   `json:"user_id"`
	Status                   string  `json:"status"`
	TotalCents               int64   `json:"total_cents"`
	AdminNotes               string  `json:"admin_notes"`
	ShippingDetailsEncrypted *string `json:"shipping_details_encrypted"`
	CreatedAt                string  `json:"created_at"`
}

type OrderItem struct {
	ID         int64 `json:"id"`
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int64 `json:"quantity"`
	PriceCents int64 `json:"price_cents"`
}

type PasskeyChallenge struct {
	ID          string `json:"id"`
	Challenge   string `json:"challenge"`
	UserID      *int64 `json:"user_id"`
	SessionData string `json:"session_data"`
	ExpiresAt   string `json:"expires_at"`
	CreatedAt   string `json:"created_at"`
}

type PasskeyCredential struct {
	ID           int64   `json:"id"`
	UserID       int64   `json:"user_id"`
	CredentialID string  `json:"credential_id"`
	PublicKey    string  `json:"public_key"`
	Counter      int64   `json:"counter"`
	Transports   *string `json:"transports"`
	CreatedAt    string  `json:"created_at"`
}

type PasswordResetToken struct {
	ID        int64   `json:"id"`
	UserID    int64   `json:"user_id"`
	TokenHash string  `json:"token_hash"`
	ExpiresAt string  `json:"expires_at"`
	UsedAt    *string `json:"used_at"`
}

type Product struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	ImagePath      string `json:"image_path"`
	PriceCents     int64  `json:"price_cents"`
	CostCents      int64  `json:"cost_cents"`
	InventoryCount int64  `json:"inventory_count"`
	IsActive       int64  `json:"is_active"`
	CreatedAt      string `json:"created_at"`
}

type Review struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	ProductID int64  `json:"product_id"`
	Rating    int64  `json:"rating"`
	Body      string `json:"body"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Session struct {
	TokenHash           string  `json:"token_hash"`
	UserID              int64   `json:"user_id"`
	CsrfToken           string  `json:"csrf_token"`
	ExpiresAt           string  `json:"expires_at"`
	RevokedAt           *string `json:"revoked_at"`
	LastAuthenticatedAt string  `json:"last_authenticated_at"`
	CreatedAt           string  `json:"created_at"`
}

type TotpBackupCode struct {
	ID        int64   `json:"id"`
	UserID    int64   `json:"user_id"`
	CodeHash  string  `json:"code_hash"`
	UsedAt    *string `json:"used_at"`
	CreatedAt string  `json:"created_at"`
}

type TotpLoginChallenge struct {
	TokenHash         string `json:"token_hash"`
	UserID            int64  `json:"user_id"`
	ReturnTo          string `json:"return_to"`
	AttemptsRemaining int64  `json:"attempts_remaining"`
	ExpiresAt         string `json:"expires_at"`
	CreatedAt         string `json:"created_at"`
}

type UploadedFile struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"user_id"`
	OriginalName string `json:"original_name"`
	StoragePath  string `json:"storage_path"`
	ContentType  string `json:"content_type"`
	CreatedAt    string `json:"created_at"`
}

type User struct {
	ID                         int64   `json:"id"`
	Email                      string  `json:"email"`
	DisplayName                string  `json:"display_name"`
	Role                       string  `json:"role"`
	PasswordHash               string  `json:"password_hash"`
	TotpSecret                 *string `json:"totp_secret"`
	PendingTotpSecret          *string `json:"pending_totp_secret"`
	TotpSecretEncrypted        *string `json:"totp_secret_encrypted"`
	PendingTotpSecretEncrypted *string `json:"pending_totp_secret_encrypted"`
	LastTotpStep               *int64  `json:"last_totp_step"`
	CreatedAt                  string  `json:"created_at"`
	UpdatedAt                  string  `json:"updated_at"`
}
