// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package dbgen

import (
	"context"
	"database/sql"
)

const approvePawPalOrder = `-- name: ApprovePawPalOrder :execrows
UPDATE orders
SET status = 'paid'
WHERE id = ? AND status = 'pending'
`

func (q *Queries) ApprovePawPalOrder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, approvePawPalOrder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id,
  status,
  total_cents,
  admin_notes,
  shipping_details_encrypted
)
VALUES (?, 'pending', ?, ?, ?)
RETURNING id
`

type CreateOrderParams struct {
	UserID                   int64   `json:"user_id"`
	TotalCents               int64   `json:"total_cents"`
	AdminNotes               string  `json:"admin_notes"`
	ShippingDetailsEncrypted *string `json:"shipping_details_encrypted"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.TotalCents,
		arg.AdminNotes,
		arg.ShippingDetailsEncrypted,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity, price_cents)
VALUES (?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int64 `json:"quantity"`
	PriceCents int64 `json:"price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceCents,
	)
	return err
}

const decrementProductInventory = `-- name: DecrementProductInventory :execresult
UPDATE products
SET inventory_count = inventory_count - ?1
WHERE id = ?2
  AND is_active = 1
  AND inventory_count >= ?1
`

type DecrementProductInventoryParams struct {
	Quantity  int64 `json:"quantity"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) DecrementProductInventory(ctx context.Context, arg DecrementProductInventoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, decrementProductInventory, arg.Quantity, arg.ProductID)
}

const deleteOrderCartItems = `-- name: DeleteOrderCartItems :exec
DELETE FROM cart_items
WHERE user_id = ?
`

func (q *Queries) DeleteOrderCartItems(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrderCartItems, userID)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
  orders.id,
  orders.user_id,
  users.display_name AS customer_name,
  users.email AS customer_email,
  orders.status,
  orders.total_cents,
  orders.admin_notes,
  orders.shipping_details_encrypted,
  orders.created_at
FROM orders
JOIN users ON users.id = orders.user_id
WHERE orders.id = ?
`

type GetOrderByIDRow struct {
	ID                       int64   `json:"id"`
	UserID                   int64   `json:"user_id"`
	CustomerName             string  `json:"customer_name"`
	CustomerEmail            string  `json:"customer_email"`
	Status                   string  `json:"status"`
	TotalCents               int64   `json:"total_cents"`
	AdminNotes               string  `json:"admin_notes"`
	ShippingDetailsEncrypted *string `json:"shipping_details_encrypted"`
	CreatedAt                string  `json:"created_at"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (GetOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.Status,
		&i.TotalCents,
		&i.AdminNotes,
		&i.ShippingDetailsEncrypted,
		&i.CreatedAt,
	)
	return i, err
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT
  orders.id,
  orders.user_id,
  users.display_name AS customer_name,
  users.email AS customer_email,
  orders.status,
  orders.total_cents,
  orders.admin_notes,
  orders.shipping_details_encrypted,
  orders.created_at
FROM orders
JOIN users ON users.id = orders.user_id
ORDER BY orders.created_at DESC, orders.id DESC
`

type ListAllOrdersRow struct {
	ID                       int64   `json:"id"`
	UserID                   int64   `json:"user_id"`
	CustomerName             string  `json:"customer_name"`
	CustomerEmail            string  `json:"customer_email"`
	Status                   string  `json:"status"`
	TotalCents               int64   `json:"total_cents"`
	AdminNotes               string  `json:"admin_notes"`
	ShippingDetailsEncrypted *string `json:"shipping_details_encrypted"`
	CreatedAt                string  `json:"created_at"`
}

func (q *Queries) ListAllOrders(ctx context.Context) ([]ListAllOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOrdersRow
	for rows.Next() {
		var i ListAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.Status,
			&i.TotalCents,
			&i.AdminNotes,
			&i.ShippingDetailsEncrypted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT
  order_items.id,
  order_items.order_id,
  order_items.product_id,
  products.name AS product_name,
  order_items.quantity,
  order_items.price_cents
FROM order_items
JOIN products ON products.id = order_items.product_id
WHERE order_items.order_id = ?
ORDER BY order_items.id
`

type ListOrderItemsRow struct {
	ID          int64  `json:"id"`
	OrderID     int64  `json:"order_id"`
	ProductID   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	Quantity    int64  `json:"quantity"`
	PriceCents  int64  `json:"price_cents"`
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]ListOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsRow
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForUser = `-- name: ListOrdersForUser :many
SELECT
  orders.id,
  orders.user_id,
  users.display_name AS customer_name,
  users.email AS customer_email,
  orders.status,
  orders.total_cents,
  orders.admin_notes,
  orders.shipping_details_encrypted,
  orders.created_at
FROM orders
JOIN users ON users.id = orders.user_id
WHERE orders.user_id = ?
ORDER BY orders.created_at DESC, orders.id DESC
`

type ListOrdersForUserRow struct {
	ID                       int64   `json:"id"`
	UserID                   int64   `json:"user_id"`
	CustomerName             string  `json:"customer_name"`
	CustomerEmail            string  `json:"customer_email"`
	Status                   string  `json:"status"`
	TotalCents               int64   `json:"total_cents"`
	AdminNotes               string  `json:"admin_notes"`
	ShippingDetailsEncrypted *string `json:"shipping_details_encrypted"`
	CreatedAt                string  `json:"created_at"`
}

func (q *Queries) ListOrdersForUser(ctx context.Context, userID int64) ([]ListOrdersForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersForUserRow
	for rows.Next() {
		var i ListOrdersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.Status,
			&i.TotalCents,
			&i.AdminNotes,
			&i.ShippingDetailsEncrypted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
