// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package dbgen

import (
	"context"
	"database/sql"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = ?1
WHERE token_hash = ?2
  AND used_at IS NULL
  AND expires_at > ?1
RETURNING user_id
`

type ConsumePasswordResetTokenParams struct {
	Now       *string `json:"now"`
	TokenHash string  `json:"token_hash"`
}

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, arg ConsumePasswordResetTokenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, consumePasswordResetToken, arg.Now, arg.TokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const consumeRemainingPasswordResetTokens = `-- name: ConsumeRemainingPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = ?1
WHERE user_id = ?2 AND used_at IS NULL
`

type ConsumeRemainingPasswordResetTokensParams struct {
	Now    *string `json:"now"`
	UserID int64   `json:"user_id"`
}

func (q *Queries) ConsumeRemainingPasswordResetTokens(ctx context.Context, arg ConsumeRemainingPasswordResetTokensParams) error {
	_, err := q.db.ExecContext(ctx, consumeRemainingPasswordResetTokens, arg.Now, arg.UserID)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	UserID    int64  `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at
FROM password_reset_tokens
WHERE token_hash = ?
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const resetUserPasswordHash = `-- name: ResetUserPasswordHash :execresult
UPDATE users
SET password_hash = ?1, updated_at = ?2
WHERE id = ?3
`

type ResetUserPasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	Now          string `json:"now"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) ResetUserPasswordHash(ctx context.Context, arg ResetUserPasswordHashParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, resetUserPasswordHash, arg.PasswordHash, arg.Now, arg.UserID)
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions
SET revoked_at = ?1
WHERE user_id = ?2 AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	Now    *string `json:"now"`
	UserID int64   `json:"user_id"`
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeUserSessions, arg.Now, arg.UserID)
	return err
}
