// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passkeys.sql

package dbgen

import (
	"context"
)

const consumePasskeyChallenge = `-- name: ConsumePasskeyChallenge :one
DELETE FROM passkey_challenges
WHERE id = ?
RETURNING id, challenge, user_id, session_data, expires_at
`

type ConsumePasskeyChallengeRow struct {
	ID          string `json:"id"`
	Challenge   string `json:"challenge"`
	UserID      *int64 `json:"user_id"`
	SessionData string `json:"session_data"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) ConsumePasskeyChallenge(ctx context.Context, id string) (ConsumePasskeyChallengeRow, error) {
	row := q.db.QueryRowContext(ctx, consumePasskeyChallenge, id)
	var i ConsumePasskeyChallengeRow
	err := row.Scan(
		&i.ID,
		&i.Challenge,
		&i.UserID,
		&i.SessionData,
		&i.ExpiresAt,
	)
	return i, err
}

const createPasskeyChallenge = `-- name: CreatePasskeyChallenge :exec
INSERT INTO passkey_challenges (id, challenge, user_id, session_data, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePasskeyChallengeParams struct {
	ID          string `json:"id"`
	Challenge   string `json:"challenge"`
	UserID      *int64 `json:"user_id"`
	SessionData string `json:"session_data"`
	ExpiresAt   string `json:"expires_at"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreatePasskeyChallenge(ctx context.Context, arg CreatePasskeyChallengeParams) error {
	_, err := q.db.ExecContext(ctx, createPasskeyChallenge,
		arg.ID,
		arg.Challenge,
		arg.UserID,
		arg.SessionData,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createPasskeyCredential = `-- name: CreatePasskeyCredential :exec
INSERT INTO passkey_credentials (user_id, credential_id, public_key, counter, transports)
VALUES (?, ?, ?, ?, ?)
`

type CreatePasskeyCredentialParams struct {
	UserID       int64   `json:"user_id"`
	CredentialID string  `json:"credential_id"`
	PublicKey    string  `json:"public_key"`
	Counter      int64   `json:"counter"`
	Transports   *string `json:"transports"`
}

func (q *Queries) CreatePasskeyCredential(ctx context.Context, arg CreatePasskeyCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createPasskeyCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.Counter,
		arg.Transports,
	)
	return err
}

const deleteExpiredPasskeyChallenges = `-- name: DeleteExpiredPasskeyChallenges :exec
DELETE FROM passkey_challenges
WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredPasskeyChallenges(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasskeyChallenges, expiresAt)
	return err
}

const deletePasskeyCredential = `-- name: DeletePasskeyCredential :exec
DELETE FROM passkey_credentials
WHERE id = ? AND user_id = ?
`

type DeletePasskeyCredentialParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePasskeyCredential(ctx context.Context, arg DeletePasskeyCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deletePasskeyCredential, arg.ID, arg.UserID)
	return err
}

const getPasskeyCredentialByCredentialID = `-- name: GetPasskeyCredentialByCredentialID :one
SELECT id, user_id, credential_id, public_key, counter, transports, created_at
FROM passkey_credentials
WHERE credential_id = ?
`

func (q *Queries) GetPasskeyCredentialByCredentialID(ctx context.Context, credentialID string) (PasskeyCredential, error) {
	row := q.db.QueryRowContext(ctx, getPasskeyCredentialByCredentialID, credentialID)
	var i PasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Counter,
		&i.Transports,
		&i.CreatedAt,
	)
	return i, err
}

const listPasskeyCredentials = `-- name: ListPasskeyCredentials :many
SELECT id, user_id, credential_id, public_key, counter, transports, created_at
FROM passkey_credentials
WHERE user_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListPasskeyCredentials(ctx context.Context, userID int64) ([]PasskeyCredential, error) {
	rows, err := q.db.QueryContext(ctx, listPasskeyCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasskeyCredential
	for rows.Next() {
		var i PasskeyCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.Counter,
			&i.Transports,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasskeyCredentialCounter = `-- name: UpdatePasskeyCredentialCounter :exec
UPDATE passkey_credentials
SET counter = ?
WHERE credential_id = ?
`

type UpdatePasskeyCredentialCounterParams struct {
	Counter      int64  `json:"counter"`
	CredentialID string `json:"credential_id"`
}

func (q *Queries) UpdatePasskeyCredentialCounter(ctx context.Context, arg UpdatePasskeyCredentialCounterParams) error {
	_, err := q.db.ExecContext(ctx, updatePasskeyCredentialCounter, arg.Counter, arg.CredentialID)
	return err
}
