// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbgen

import (
	"context"
)

const getActiveProduct = `-- name: GetActiveProduct :one
SELECT id, name, description, image_path, price_cents, cost_cents, inventory_count, is_active, created_at
FROM products
WHERE id = ? AND is_active = 1
`

func (q *Queries) GetActiveProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getActiveProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImagePath,
		&i.PriceCents,
		&i.CostCents,
		&i.InventoryCount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, description, image_path, price_cents, cost_cents, inventory_count, is_active, created_at
FROM products
WHERE is_active = 1
ORDER BY name
LIMIT ?
`

func (q *Queries) ListActiveProducts(ctx context.Context, limit int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImagePath,
			&i.PriceCents,
			&i.CostCents,
			&i.InventoryCount,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForProduct = `-- name: ListReviewsForProduct :many
SELECT
  reviews.id,
  reviews.user_id,
  reviews.product_id,
  products.name AS product_name,
  users.display_name AS reviewer_name,
  reviews.rating,
  reviews.body,
  reviews.created_at,
  reviews.updated_at
FROM reviews
JOIN users ON users.id = reviews.user_id
JOIN products ON products.id = reviews.product_id
WHERE reviews.product_id = ?
ORDER BY reviews.created_at DESC, reviews.id DESC
`

type ListReviewsForProductRow struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"user_id"`
	ProductID    int64  `json:"product_id"`
	ProductName  string `json:"product_name"`
	ReviewerName string `json:"reviewer_name"`
	Rating       int64  `json:"rating"`
	Body         string `json:"body"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) ListReviewsForProduct(ctx context.Context, productID int64) ([]ListReviewsForProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsForProductRow
	for rows.Next() {
		var i ListReviewsForProductRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.ProductName,
			&i.ReviewerName,
			&i.Rating,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchActiveProducts = `-- name: SearchActiveProducts :many
SELECT id, name, description, image_path, price_cents, cost_cents, inventory_count, is_active, created_at
FROM products
WHERE is_active = 1
  AND (name LIKE ?1 OR description LIKE ?1)
ORDER BY name
LIMIT ?2
`

type SearchActiveProductsParams struct {
	Pattern    string `json:"pattern"`
	MaxResults int64  `json:"max_results"`
}

func (q *Queries) SearchActiveProducts(ctx context.Context, arg SearchActiveProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchActiveProducts, arg.Pattern, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImagePath,
			&i.PriceCents,
			&i.CostCents,
			&i.InventoryCount,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
