// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package dbgen

import (
	"context"
)

const activeReviewProductExists = `-- name: ActiveReviewProductExists :one
SELECT EXISTS(
  SELECT 1
  FROM products
  WHERE id = ? AND is_active = 1
)
`

func (q *Queries) ActiveReviewProductExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeReviewProductExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createReview = `-- name: CreateReview :exec
INSERT INTO reviews (user_id, product_id, rating, body)
VALUES (?, ?, ?, ?)
`

type CreateReviewParams struct {
	UserID    int64  `json:"user_id"`
	ProductID int64  `json:"product_id"`
	Rating    int64  `json:"rating"`
	Body      string `json:"body"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) error {
	_, err := q.db.ExecContext(ctx, createReview,
		arg.UserID,
		arg.ProductID,
		arg.Rating,
		arg.Body,
	)
	return err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews
WHERE id = ?
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReview, id)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT
  reviews.id,
  reviews.user_id,
  reviews.product_id,
  products.name AS product_name,
  users.display_name AS reviewer_name,
  reviews.rating,
  reviews.body,
  reviews.created_at,
  reviews.updated_at
FROM reviews
JOIN users ON users.id = reviews.user_id
JOIN products ON products.id = reviews.product_id
WHERE reviews.id = ?
`

type GetReviewByIDRow struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"user_id"`
	ProductID    int64  `json:"product_id"`
	ProductName  string `json:"product_name"`
	ReviewerName string `json:"reviewer_name"`
	Rating       int64  `json:"rating"`
	Body         string `json:"body"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) GetReviewByID(ctx context.Context, id int64) (GetReviewByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i GetReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.ProductName,
		&i.ReviewerName,
		&i.Rating,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsForUser = `-- name: ListReviewsForUser :many
SELECT
  reviews.id,
  reviews.user_id,
  reviews.product_id,
  products.name AS product_name,
  users.display_name AS reviewer_name,
  reviews.rating,
  reviews.body,
  reviews.created_at,
  reviews.updated_at
FROM reviews
JOIN users ON users.id = reviews.user_id
JOIN products ON products.id = reviews.product_id
WHERE reviews.user_id = ?
ORDER BY reviews.created_at DESC, reviews.id DESC
`

type ListReviewsForUserRow struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"user_id"`
	ProductID    int64  `json:"product_id"`
	ProductName  string `json:"product_name"`
	ReviewerName string `json:"reviewer_name"`
	Rating       int64  `json:"rating"`
	Body         string `json:"body"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) ListReviewsForUser(ctx context.Context, userID int64) ([]ListReviewsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsForUserRow
	for rows.Next() {
		var i ListReviewsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.ProductName,
			&i.ReviewerName,
			&i.Rating,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE reviews
SET rating = ?, body = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateReviewParams struct {
	Rating int64  `json:"rating"`
	Body   string `json:"body"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview, arg.Rating, arg.Body, arg.ID)
	return err
}
