// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package dbgen

import (
	"context"
)

const deleteAPIKeyUsage = `-- name: DeleteAPIKeyUsage :exec
DELETE FROM api_key_usage
`

func (q *Queries) DeleteAPIKeyUsage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKeyUsage)
	return err
}

const deleteAPIKeys = `-- name: DeleteAPIKeys :exec
DELETE FROM api_keys
`

func (q *Queries) DeleteAPIKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKeys)
	return err
}

const deleteCartItems = `-- name: DeleteCartItems :exec
DELETE FROM cart_items
`

func (q *Queries) DeleteCartItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteCartItems)
	return err
}

const deleteImportedTaxDocuments = `-- name: DeleteImportedTaxDocuments :exec
DELETE FROM imported_tax_documents
`

func (q *Queries) DeleteImportedTaxDocuments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteImportedTaxDocuments)
	return err
}

const deleteMFARecoveryAttempts = `-- name: DeleteMFARecoveryAttempts :exec
DELETE FROM mfa_recovery_attempts
`

func (q *Queries) DeleteMFARecoveryAttempts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMFARecoveryAttempts)
	return err
}

const deleteOrderItems = `-- name: DeleteOrderItems :exec
DELETE FROM order_items
`

func (q *Queries) DeleteOrderItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItems)
	return err
}

const deleteOrders = `-- name: DeleteOrders :exec
DELETE FROM orders
`

func (q *Queries) DeleteOrders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrders)
	return err
}

const deletePasskeyChallenges = `-- name: DeletePasskeyChallenges :exec
DELETE FROM passkey_challenges
`

func (q *Queries) DeletePasskeyChallenges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePasskeyChallenges)
	return err
}

const deletePasskeyCredentials = `-- name: DeletePasskeyCredentials :exec
DELETE FROM passkey_credentials
`

func (q *Queries) DeletePasskeyCredentials(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePasskeyCredentials)
	return err
}

const deletePasswordResetTokens = `-- name: DeletePasswordResetTokens :exec
DELETE FROM password_reset_tokens
`

func (q *Queries) DeletePasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetTokens)
	return err
}

const deleteProducts = `-- name: DeleteProducts :exec
DELETE FROM products
`

func (q *Queries) DeleteProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteProducts)
	return err
}

const deleteReviews = `-- name: DeleteReviews :exec
DELETE FROM reviews
`

func (q *Queries) DeleteReviews(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteReviews)
	return err
}

const deleteSessions = `-- name: DeleteSessions :exec
DELETE FROM sessions
`

func (q *Queries) DeleteSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSessions)
	return err
}

const deleteTOTPBackupCodes = `-- name: DeleteTOTPBackupCodes :exec
DELETE FROM totp_backup_codes
`

func (q *Queries) DeleteTOTPBackupCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTOTPBackupCodes)
	return err
}

const deleteTOTPLoginChallenges = `-- name: DeleteTOTPLoginChallenges :exec
DELETE FROM totp_login_challenges
`

func (q *Queries) DeleteTOTPLoginChallenges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTOTPLoginChallenges)
	return err
}

const deleteUploadedFiles = `-- name: DeleteUploadedFiles :exec
DELETE FROM uploaded_files
`

func (q *Queries) DeleteUploadedFiles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUploadedFiles)
	return err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id FROM users WHERE email = ?
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmail, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSeedAPIKey = `-- name: InsertSeedAPIKey :exec
INSERT INTO api_keys (name, key_hash, scope)
VALUES (?, ?, ?)
`

type InsertSeedAPIKeyParams struct {
	Name    string `json:"name"`
	KeyHash string `json:"key_hash"`
	Scope   string `json:"scope"`
}

func (q *Queries) InsertSeedAPIKey(ctx context.Context, arg InsertSeedAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedAPIKey, arg.Name, arg.KeyHash, arg.Scope)
	return err
}

const insertSeedOrder = `-- name: InsertSeedOrder :exec
INSERT INTO orders (user_id, status, total_cents, admin_notes)
VALUES (?, ?, ?, ?)
`

type InsertSeedOrderParams struct {
	UserID     int64  `json:"user_id"`
	Status     string `json:"status"`
	TotalCents int64  `json:"total_cents"`
	AdminNotes string `json:"admin_notes"`
}

func (q *Queries) InsertSeedOrder(ctx context.Context, arg InsertSeedOrderParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedOrder,
		arg.UserID,
		arg.Status,
		arg.TotalCents,
		arg.AdminNotes,
	)
	return err
}

const insertSeedOrderItem = `-- name: InsertSeedOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity, price_cents)
VALUES (?, ?, ?, ?)
`

type InsertSeedOrderItemParams struct {
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int64 `json:"quantity"`
	PriceCents int64 `json:"price_cents"`
}

func (q *Queries) InsertSeedOrderItem(ctx context.Context, arg InsertSeedOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceCents,
	)
	return err
}

const insertSeedPasskeyCredential = `-- name: InsertSeedPasskeyCredential :exec
INSERT INTO passkey_credentials (user_id, credential_id, public_key, counter, transports)
VALUES (?, ?, ?, 0, ?)
`

type InsertSeedPasskeyCredentialParams struct {
	UserID       int64   `json:"user_id"`
	CredentialID string  `json:"credential_id"`
	PublicKey    string  `json:"public_key"`
	Transports   *string `json:"transports"`
}

func (q *Queries) InsertSeedPasskeyCredential(ctx context.Context, arg InsertSeedPasskeyCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedPasskeyCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.Transports,
	)
	return err
}

const insertSeedProduct = `-- name: InsertSeedProduct :exec
INSERT INTO products (
  name,
  description,
  image_path,
  price_cents,
  cost_cents,
  inventory_count,
  is_active
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSeedProductParams struct {
	Name           string `json:"name"`
	Description    string `json:"description"`
	ImagePath      string `json:"image_path"`
	PriceCents     int64  `json:"price_cents"`
	CostCents      int64  `json:"cost_cents"`
	InventoryCount int64  `json:"inventory_count"`
	IsActive       int64  `json:"is_active"`
}

func (q *Queries) InsertSeedProduct(ctx context.Context, arg InsertSeedProductParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedProduct,
		arg.Name,
		arg.Description,
		arg.ImagePath,
		arg.PriceCents,
		arg.CostCents,
		arg.InventoryCount,
		arg.IsActive,
	)
	return err
}

const insertSeedReview = `-- name: InsertSeedReview :exec
INSERT INTO reviews (user_id, product_id, rating, body)
VALUES (?, ?, ?, ?)
`

type InsertSeedReviewParams struct {
	UserID    int64  `json:"user_id"`
	ProductID int64  `json:"product_id"`
	Rating    int64  `json:"rating"`
	Body      string `json:"body"`
}

func (q *Queries) InsertSeedReview(ctx context.Context, arg InsertSeedReviewParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedReview,
		arg.UserID,
		arg.ProductID,
		arg.Rating,
		arg.Body,
	)
	return err
}

const insertSeedTOTPBackupCode = `-- name: InsertSeedTOTPBackupCode :exec
INSERT INTO totp_backup_codes (user_id, code_hash)
VALUES (?, ?)
`

type InsertSeedTOTPBackupCodeParams struct {
	UserID   int64  `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) InsertSeedTOTPBackupCode(ctx context.Context, arg InsertSeedTOTPBackupCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedTOTPBackupCode, arg.UserID, arg.CodeHash)
	return err
}

const insertSeedUploadedFile = `-- name: InsertSeedUploadedFile :exec
INSERT INTO uploaded_files (user_id, original_name, storage_path, content_type)
VALUES (?, ?, ?, ?)
`

type InsertSeedUploadedFileParams struct {
	UserID       int64  `json:"user_id"`
	OriginalName string `json:"original_name"`
	StoragePath  string `json:"storage_path"`
	ContentType  string `json:"content_type"`
}

func (q *Queries) InsertSeedUploadedFile(ctx context.Context, arg InsertSeedUploadedFileParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedUploadedFile,
		arg.UserID,
		arg.OriginalName,
		arg.StoragePath,
		arg.ContentType,
	)
	return err
}

const insertSeedUser = `-- name: InsertSeedUser :exec
INSERT INTO users (email, display_name, role, password_hash)
VALUES (?, ?, ?, ?)
`

type InsertSeedUserParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	Role         string `json:"role"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) InsertSeedUser(ctx context.Context, arg InsertSeedUserParams) error {
	_, err := q.db.ExecContext(ctx, insertSeedUser,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.PasswordHash,
	)
	return err
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :exec
UPDATE users SET totp_secret = ? WHERE email = ?
`

type SetUserTOTPSecretParams struct {
	TotpSecret *string `json:"totp_secret"`
	Email      string  `json:"email"`
}

func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, setUserTOTPSecret, arg.TotpSecret, arg.Email)
	return err
}
