// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploads.sql

package dbgen

import (
	"context"
)

const createImportedTaxDocument = `-- name: CreateImportedTaxDocument :one
INSERT INTO imported_tax_documents (imported_by_user_id, original_name, storage_path, content_type)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateImportedTaxDocumentParams struct {
	ImportedByUserID int64  `json:"imported_by_user_id"`
	OriginalName     string `json:"original_name"`
	StoragePath      string `json:"storage_path"`
	ContentType      string `json:"content_type"`
}

func (q *Queries) CreateImportedTaxDocument(ctx context.Context, arg CreateImportedTaxDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createImportedTaxDocument,
		arg.ImportedByUserID,
		arg.OriginalName,
		arg.StoragePath,
		arg.ContentType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUploadedFile = `-- name: CreateUploadedFile :one
INSERT INTO uploaded_files (user_id, original_name, storage_path, content_type)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateUploadedFileParams struct {
	UserID       int64  `json:"user_id"`
	OriginalName string `json:"original_name"`
	StoragePath  string `json:"storage_path"`
	ContentType  string `json:"content_type"`
}

func (q *Queries) CreateUploadedFile(ctx context.Context, arg CreateUploadedFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUploadedFile,
		arg.UserID,
		arg.OriginalName,
		arg.StoragePath,
		arg.ContentType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getImportedTaxDocumentByID = `-- name: GetImportedTaxDocumentByID :one
SELECT
  imported_tax_documents.id,
  imported_tax_documents.imported_by_user_id,
  users.display_name AS imported_by_name,
  imported_tax_documents.original_name,
  imported_tax_documents.storage_path,
  imported_tax_documents.content_type,
  imported_tax_documents.created_at
FROM imported_tax_documents
JOIN users ON users.id = imported_tax_documents.imported_by_user_id
WHERE imported_tax_documents.id = ?
`

type GetImportedTaxDocumentByIDRow struct {
	ID               int64  `json:"id"`
	ImportedByUserID int64  `json:"imported_by_user_id"`
	ImportedByName   string `json:"imported_by_name"`
	OriginalName     string `json:"original_name"`
	StoragePath      string `json:"storage_path"`
	ContentType      string `json:"content_type"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) GetImportedTaxDocumentByID(ctx context.Context, id int64) (GetImportedTaxDocumentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getImportedTaxDocumentByID, id)
	var i GetImportedTaxDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ImportedByUserID,
		&i.ImportedByName,
		&i.OriginalName,
		&i.StoragePath,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadedFileByID = `-- name: GetUploadedFileByID :one
SELECT
  uploaded_files.id,
  uploaded_files.user_id,
  users.display_name AS customer_name,
  users.email AS customer_email,
  uploaded_files.original_name,
  uploaded_files.storage_path,
  uploaded_files.content_type,
  uploaded_files.created_at
FROM uploaded_files
JOIN users ON users.id = uploaded_files.user_id
WHERE uploaded_files.id = ?
`

type GetUploadedFileByIDRow struct {
	ID            int64  `json:"id"`
	UserID        int64  `json:"user_id"`
	CustomerName  string `json:"customer_name"`
	CustomerEmail string `json:"customer_email"`
	OriginalName  string `json:"original_name"`
	StoragePath   string `json:"storage_path"`
	ContentType   string `json:"content_type"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) GetUploadedFileByID(ctx context.Context, id int64) (GetUploadedFileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUploadedFileByID, id)
	var i GetUploadedFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.OriginalName,
		&i.StoragePath,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUploadedFiles = `-- name: ListAllUploadedFiles :many
SELECT
  uploaded_files.id,
  uploaded_files.user_id,
  users.display_name AS customer_name,
  users.email AS customer_email,
  uploaded_files.original_name,
  uploaded_files.storage_path,
  uploaded_files.content_type,
  uploaded_files.created_at
FROM uploaded_files
JOIN users ON users.id = uploaded_files.user_id
ORDER BY uploaded_files.created_at DESC, uploaded_files.id DESC
`

type ListAllUploadedFilesRow struct {
	ID            int64  `json:"id"`
	UserID        int64  `json:"user_id"`
	CustomerName  string `json:"customer_name"`
	CustomerEmail string `json:"customer_email"`
	OriginalName  string `json:"original_name"`
	StoragePath   string `json:"storage_path"`
	ContentType   string `json:"content_type"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) ListAllUploadedFiles(ctx context.Context) ([]ListAllUploadedFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllUploadedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUploadedFilesRow
	for rows.Next() {
		var i ListAllUploadedFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.OriginalName,
			&i.StoragePath,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedTaxDocuments = `-- name: ListImportedTaxDocuments :many
SELECT
  imported_tax_documents.id,
  imported_tax_documents.imported_by_user_id,
  users.display_name AS imported_by_name,
  imported_tax_documents.original_name,
  imported_tax_documents.storage_path,
  imported_tax_documents.content_type,
  imported_tax_documents.created_at
FROM imported_tax_documents
JOIN users ON users.id = imported_tax_documents.imported_by_user_id
ORDER BY imported_tax_documents.created_at DESC, imported_tax_documents.id DESC
`

type ListImportedTaxDocumentsRow struct {
	ID               int64  `json:"id"`
	ImportedByUserID int64  `json:"imported_by_user_id"`
	ImportedByName   string `json:"imported_by_name"`
	OriginalName     string `json:"original_name"`
	StoragePath      string `json:"storage_path"`
	ContentType      string `json:"content_type"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) ListImportedTaxDocuments(ctx context.Context) ([]ListImportedTaxDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listImportedTaxDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportedTaxDocumentsRow
	for rows.Next() {
		var i ListImportedTaxDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportedByUserID,
			&i.ImportedByName,
			&i.OriginalName,
			&i.StoragePath,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaintextImportedTaxDocuments = `-- name: ListPlaintextImportedTaxDocuments :many
SELECT id, original_name, storage_path
FROM imported_tax_documents
WHERE storage_path NOT LIKE '%.enc'
`

type ListPlaintextImportedTaxDocumentsRow struct {
	ID           int64  `json:"id"`
	OriginalName string `json:"original_name"`
	StoragePath  string `json:"storage_path"`
}

func (q *Queries) ListPlaintextImportedTaxDocuments(ctx context.Context) ([]ListPlaintextImportedTaxDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaintextImportedTaxDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaintextImportedTaxDocumentsRow
	for rows.Next() {
		var i ListPlaintextImportedTaxDocumentsRow
		if err := rows.Scan(&i.ID, &i.OriginalName, &i.StoragePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaintextUploadedFiles = `-- name: ListPlaintextUploadedFiles :many
SELECT id, original_name, storage_path
FROM uploaded_files
WHERE storage_path NOT LIKE '%.enc'
`

type ListPlaintextUploadedFilesRow struct {
	ID           int64  `json:"id"`
	OriginalName string `json:"original_name"`
	StoragePath  string `json:"storage_path"`
}

func (q *Queries) ListPlaintextUploadedFiles(ctx context.Context) ([]ListPlaintextUploadedFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaintextUploadedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaintextUploadedFilesRow
	for rows.Next() {
		var i ListPlaintextUploadedFilesRow
		if err := rows.Scan(&i.ID, &i.OriginalName, &i.StoragePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadedFilesForUser = `-- name: ListUploadedFilesForUser :many
SELECT
  uploaded_files.id,
  uploaded_files.user_id,
  users.display_name AS customer_name,
  users.email AS customer_email,
  uploaded_files.original_name,
  uploaded_files.storage_path,
  uploaded_files.content_type,
  uploaded_files.created_at
FROM uploaded_files
JOIN users ON users.id = uploaded_files.user_id
WHERE uploaded_files.user_id = ?
ORDER BY uploaded_files.created_at DESC, uploaded_files.id DESC
`

type ListUploadedFilesForUserRow struct {
	ID            int64  `json:"id"`
	UserID        int64  `json:"user_id"`
	CustomerName  string `json:"customer_name"`
	CustomerEmail string `json:"customer_email"`
	OriginalName  string `json:"original_name"`
	StoragePath   string `json:"storage_path"`
	ContentType   string `json:"content_type"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) ListUploadedFilesForUser(ctx context.Context, userID int64) ([]ListUploadedFilesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listUploadedFilesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUploadedFilesForUserRow
	for rows.Next() {
		var i ListUploadedFilesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.OriginalName,
			&i.StoragePath,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportedTaxDocumentStorage = `-- name: UpdateImportedTaxDocumentStorage :exec
UPDATE imported_tax_documents
SET storage_path = ?, content_type = ?
WHERE id = ?
`

type UpdateImportedTaxDocumentStorageParams struct {
	StoragePath string `json:"storage_path"`
	ContentType string `json:"content_type"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateImportedTaxDocumentStorage(ctx context.Context, arg UpdateImportedTaxDocumentStorageParams) error {
	_, err := q.db.ExecContext(ctx, updateImportedTaxDocumentStorage, arg.StoragePath, arg.ContentType, arg.ID)
	return err
}

const updateUploadedFileStorage = `-- name: UpdateUploadedFileStorage :exec
UPDATE uploaded_files
SET storage_path = ?, content_type = ?
WHERE id = ?
`

type UpdateUploadedFileStorageParams struct {
	StoragePath string `json:"storage_path"`
	ContentType string `json:"content_type"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUploadedFileStorage(ctx context.Context, arg UpdateUploadedFileStorageParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadedFileStorage, arg.StoragePath, arg.ContentType, arg.ID)
	return err
}
